print("hello, this is python programming")
print("2+5")
print("\n")
print("5-9")
print("\n")
print("8/2")
print("\n")
print("8*9/6+22-4")
print("now i'll talk about myself :>")
print("my name is soyinka abdulhamid")
print("i am 13 yrs old")
print("im in grade 9, and my favorite game is roblox")
print("my favorite sports are football and basketball")
print("my hobbies are either reading books, or watching tv or playing gamed when im free :)")
print("the end :>")

print("keywords in python")
import keyword
print(keyword.kwlist)